# Generated by Django 4.0.4 on 2022-05-08 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giverly', '0003_alter_order_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='giverly.event'),
        ),
    ]
